export  const GuideActionTypes = {
    TOGGLE_CREATE_EVENT_HIDDEN: 'TOGGLE_CREATE_EVENT_HIDDEN',
    TOGGLE_PRIVATE_EVENT: 'TOGGLE_PRIVATE_EVENT',
    INCREASE_GAME_VOTE: 'INCREASE_GAME_VOTE',
    DECREASE_GAME_VOTE: 'DECREASE_GAME_VOTE',
    INCREASE_REMAINING_USER_VOTES: 'INCREASE_REMAINING_USER_VOTES',
    DECREASE_REMAINING_USER_VOTES:'DECREASE_REMAINING_USER_VOTES',
    SET_ACTIVE_EVENT_ID:'SET_ACTIVE_EVENT_ID:'
}