export  const GuideActionTypes = {
    SET_CURRENT_EVENT:' SET_CURRENT_EVENT',
    TOGGLE_CREATE_EVENT_HIDDEN: 'TOGGLE_CREATE_EVENT_HIDDEN',
    TOGGLE_PRIVATE_EVENT: 'TOGGLE_PRIVATE_EVENT',
    INCREASE_GAME_VOTE: 'INCREASE_GAME_VOTE',
    DECREASE_GAME_VOTE: 'DECREASE_GAME_VOTE'
}